FROM node:20-alpine
RUN apk add --no-cache openssl

WORKDIR /app
ENV NODE_ENV=production

ARG DATABASE_URL
ARG SHOPIFY_API_KEY
ARG SHOPIFY_API_SECRET
ENV DATABASE_URL=$DATABASE_URL
ENV SHOPIFY_API_KEY=$SHOPIFY_API_KEY
ENV SHOPIFY_API_SECRET=$SHOPIFY_API_SECRET

COPY package.json package-lock.json* ./
RUN npm ci --omit=dev && npm cache clean --force

COPY . .

CMD ["npm", "run", "worker-start"]
